-- ===============TREINO_ACADEMIA===============
CREATE DATABASE IF NOT EXISTS TREINO_ACADEMIA;
USE TREINO_ACADEMIA;

CREATE TABLE PLANO(
    ID_PLANO INT AUTO_INCREMENT,
    NOME_PLANO VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    PRIMARY KEY(ID_PLANO)
);

CREATE TABLE ALUNO(
    ID_ALUNO INT AUTO_INCREMENT,
    NOME_ALUNO VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(30) DEFAULT "Musculacao",
    ID_PLANO INT NOT NULL,
    PRIMARY KEY(ID_ALUNO),
    FOREIGN KEY(ID_PLANO) REFERENCES PLANO(ID_PLANO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

SHOW TABLES;
DESC PLANO;
DESC ALUNO;

ALTER TABLE ALUNO ADD COLUMN TELEFONE VARCHAR(20) AFTER NOME_ALUNO;
ALTER TABLE ALUNO MODIFY COLUMN CATEGORIA VARCHAR(50)DEFAULT "Musculacao";
 ALTER TABLE ALUNO CHANGE COLUMN TELEFONE  NUMERO_TELEFONE VARCHAR(20);
 ALTER TABLE ALUNO DROP COLUMN TELEFONE;  

INSERT INTO PLANO(NOME_PLANO, VALOR)
VALUES  ("Smart", 110.0),
        ("Black", 140.0);
 INSERT INTO ALUNO(NOME_ALUNO, TELEFONE, CATEGORIA, ID_PLANO)
 VALUES ("Tiago", "12345689", "natacao", 1),
        ("Murilo","4567891230", "crossfit", 1);
INSERT INTO ALUNO(NOME_ALUNO, TELEFONE, ID_PLANO)
VALUES  ("Marquin", "1234567654", 2);
 
 SELECT *FROM ALUNO WHERE NOME_ALUNO LIKE "%O";
 SELECT *FROM ALUNO WHERE CATEGORIA = "natacao" OR CATEGORIA ="crossfit";
 SELECT *FROM plano WHERE VALOR NOT BETWEEN 100 AND 120;
SELECT *FROM PLANO WHERE VALOR IN (140);


SELECT a.NOME_ALUNO, p.VALOR 
FROM PLANO p LEFT join ALUNO a 
ON a.`ID_PLANO` = p.`ID_PLANO`; 


SHOW TABLES;
DESC ALUNO;
DESC PLANO;

SELECT p.NOME_PLANO, SUM(p.VALOR) AS VALOR_TOTAL
FROM PLANO p JOIN ALUNO a ON
p.ID_PLANO = a.iD_PLANO
GROUP BY p.NOME_PLANO;


SELECT CATEGORIA, COUNT(*) AS CATEGORIA
FROM ALUNO
GROUP BY CATEGORIA;

SELECT a.CATEGORIA, AVG(VALOR) AS MEDIA_CATEGORIA
FROM ALUNO a JOIN PLANO p ON 
a.ID_PLANO = p.ID_PLANO
WHERE a.CATEGORIA = "Natacao"
GROUP BY a.CATEGORIA;

SELECT a.CATEGORIA, SUM(p.VALOR) AS VALOR_CATEGORIAS
FROM ALUNO a JOIN PLANO p ON
a.ID_PLANO = p.ID_PLANO
WHERE p.VALOR >120.00
GROUP BY a.CATEGORIA;


SELECT 