--==============================SISTEMA DE GESTAO DE PRODUTOS==============================
CREATE DATABASE IF NOT EXISTS SISTEMA_GESTAO_PRODUTOS ;
USE   SISTEMA_GESTAO_PRODUTOS;

CREATE TABLE FORNECEDOR(

    ID_FORNECEDOR INT AUTO_INCREMENT,
    NOME_EMPRESA VARCHAR(100) NOT NULL,
    PAIS_ORIGEM VARCHAR(50) DEFAULT "Brasil",
    PRIMARY KEY(ID_FORNECEDOR)

);

CREATE TABLE PRODUTO(
    ID_PRODUTO INT AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    QUANTIDADE_ESTOQUE INT DEFAULT 0,
    ID_FORNECEDOR INT,
    PRIMARY KEY(ID_PRODUTO),
    FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR) ON UPDATE RESTRICT ON DELETE RESTRICT
)

SHOW TABLES;
DESC PRODUTO;
DESC FORNECEDOR;

INSERT INTO FORNECEDOR(NOME_EMPRESA, PAIS_ORIGEM)
VALUES   ("Tech Imports S/A","China");
INSERT INTO FORNECEDOR(NOME_EMPRESA)
VALUES   ("Distribuidora Sul Alimentos");
SELECT *FROM FORNECEDOR;

INSERT INTO PRODUTO(NOME_PRODUTO, CATEGORIA, PRECO_UNITARIO, QUANTIDADE_ESTOQUE, ID_FORNECEDOR)
VALUES   ("Teclado Mecânico","Eletronicos", 250.00, 15, 1),
         ("Mouse Gamer","Eletronicos",120.00,8, 1),
         ("Arroz Integral 5kg", "Alimentos", 30.00, 50, 2),
         ("Feijão Preto 1kg", "Alimentos", 9.50, 12, 2);
SELECT *FROM PRODUTO;