--==============================SISTEMA DE GESTAO DE PRODUTOS==============================
CREATE DATABASE IF NOT EXISTS SISTEMA_GESTAO_PRODUTOS ;
USE   SISTEMA_GESTAO_PRODUTOS;

CREATE TABLE FORNECEDOR(

    ID_FORNECEDOR INT AUTO_INCREMENT,
    NOME_EMPRESA VARCHAR(100) NOT NULL,
    PAIS_ORIGEM VARCHAR(50) DEFAULT "Brasil",
    PRIMARY KEY(ID_FORNECEDOR)

);

CREATE TABLE PRODUTO(
    ID_PRODUTO INT AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    QUANTIDADE_ESTOQUE INT DEFAULT 0,
    ID_FORNECEDOR INT,
    PRIMARY KEY(ID_PRODUTO),
    FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR) ON UPDATE RESTRICT ON DELETE RESTRICT
)

SHOW TABLES;
DESC PRODUTO;
DESC FORNECEDOR;

INSERT INTO FORNECEDOR(NOME_EMPRESA, PAIS_ORIGEM)
VALUES   ("Tech Imports S/A","China");
INSERT INTO FORNECEDOR(NOME_EMPRESA)
VALUES   ("Distribuidora Sul Alimentos");
SELECT *FROM FORNECEDOR;

INSERT INTO PRODUTO(NOME_PRODUTO, CATEGORIA, PRECO_UNITARIO, QUANTIDADE_ESTOQUE, ID_FORNECEDOR)
VALUES   ("Teclado Mecânico","Eletronicos", 250.00, 15, 1),
         ("Mouse Gamer","Eletronicos",120.00,8, 1),
         ("Arroz Integral 5kg", "Alimentos", 30.00, 50, 2),
         ("Feijão Preto 1kg", "Alimentos", 9.50, 12, 2);
SELECT *FROM PRODUTO;

SELECT *FROM PRODUTO
WHERE PRECO_UNITARIO BETWEEN 10 AND 300 
AND CATEGORIA NOT LIKE "Alimentos";

SELECT p.CATEGORIA, SUM(p.PRECO_UNITARIO * p.QUANTIDADE_ESTOQUE) AS VALOR_TOTAL
FROM PRODUTO p JOIN FORNECEDOR f ON
f.ID_FORNECEDOR = p.ID_FORNECEDOR
GROUP BY p.CATEGORIA;

SELECT f.NOME_EMPRESA, COUNT(p.ID_FORNECEDOR) AS QUANTIDADES_PRODUTO
FROM PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR
GROUP BY f.NOME_EMPRESA;

SELECT f.NOME_EMPRESA, MAX(p.PRECO_UNITARIO) AS VALOR_MAXIMO,
MIN(p.PRECO_UNITARIO) AS VALOR_MINIMO FROM
PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR
GROUP BY f.NOME_EMPRESA;

SELECT  f.NOME_EMPRESA, SUM(p.PRECO_UNITARIO * p.QUANTIDADE_ESTOQUE) AS VALOR_ESTOQUE
FROM PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR 
GROUP BY f.NOME_EMPRESA;

SELECT p.CATEGORIA, SUM(p.QUANTIDADE_ESTOQUE) AS QUANTIDADE_CATEGORIA
FROM PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR
GROUP BY p.CATEGORIA
HAVING SUM(p.QUANTIDADE_ESTOQUE) > 15;


SELECT f.NOME_EMPRESA, AVG(p.PRECO_UNITARIO) AS VALOR_MEDIO
FROM PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR 
WHERE f.PAIS_ORIGEM NOT LIKE 'Brasil'
GROUP BY f.NOME_EMPRESA
HAVING AVG(p.PRECO_UNITARIO) > 100;

SELECT p.CATEGORIA, SUM(p.QUANTIDADE_ESTOQUE) AS ITENS_BARATOS
FROM PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR 
WHERE p.PRECO_UNITARIO < 50.0
GROUP BY p.CATEGORIA
HAVING SUM(p.QUANTIDADE_ESTOQUE) > 30;

SELECT f.NOME_EMPRESA, COUNT(p.ID_PRODUTO) AS FORNECEDORES_ATIVOS
FROM PRODUTO p JOIN FORNECEDOR f ON
p.ID_FORNECEDOR = f.ID_FORNECEDOR 
WHERE p.PRECO_UNITARIO > 10 
GROUP BY f.NOME_EMPRESA 
HAVING COUNT(p.ID_PRODUTO) > 1;