--==========================DB_PLATAFORMA==========================

CREATE DATABASE DB_PLATAFORMA;
USE DB_PLATAFORMA;

CREATE TABLE EMPRESA(
    ID_EMPRESA INT AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(80) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    PRIMARY KEY(ID_EMPRESA)
);
CREATE TABLE CONTRATO(
    ID_CONTRATO INT AUTO_INCREMENT,
    PLANO_CONTRATO VARCHAR (40) NOT NULL,
    VALRO_MENSALIDADE DECIMAL(10,2) NOT NULL,
    DATA_ASSINATURA DATE NOT NULL,
    STATUS_CONTRATO VARCHAR(20) DEFAULT "Ativo",
    SITUACAO_FINANCEIRA VARCHAR(20) DEFAULT "Regular",
    ID_EMPRESA INT NOT NULL,
    PRIMARY KEY(ID_CONTRATO),
    FOREIGN KEY(ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)ON UPDATE RESTRICT ON DELETE RESTRICT  
);

SHOW TABLES;
DESC EMPRESA;
DESC CONTRATO;
 ALTER TABLE CONTRATO CHANGE COLUMN VALRO_MENSALIDADE VALOR_MENSALIDADE DECIMAL(10,2) NOT NULL; 
INSERT INTO EMPRESA(RAZAO_SOCIAL, CNPJ)
VALUES  ("Tech Paraná Software LTDA", "11.222.333/0001-44"),
        ("Logística Ponta Grossa S/A", "55.666.777/0001-88"),
        ("Alimentos Campos Gerais","99.000.111/0001-99");
INSERT INTO CONTRATO(PLANO_CONTRATO, VALOR_MENSALIDADE, DATA_ASSINATURA, STATUS_CONTRATO, SITUACAO_FINANCEIRA, ID_EMPRESA)
VALUES  ("Premium", 250.00, '2025-06-15', "Ativo", "Regular", 1),
        ("Enterprise", 1200.00, '2026-01-10', "Ativo", "Inadimplente", 2),
        ("Standard", 150.00, '2026-02-20', "Ativo", "Regular", 1),
        ("Premium", 250.00, '2026-03-05', "Suspenso", "Inadimplente",  3),
        ("Enterprise", 1500.00, '2026-04-12', "Ativo", "Regular", 3);

SELECT *FROM EMPRESA ;
SELECT *FROM CONTRATO where STATUS_CONTRATO LIKE "Suspenso";

SELECT e.RAZAO_SOCIAL, SUM(c.VALOR_MENSALIDADE) AS TOTAL_MENSALIDADES
FROM EMPRESA e JOIN CONTRATO c ON
e.ID_EMPRESA = c.ID_EMPRESA
WHERE c.DATA_ASSINATURA >= "2026-01-01" AND E.RAZAO_SOCIAL NOT LIKE "Logística%"
GROUP BY e.RAZAO_SOCIAL;

SELECT c.PLANO_CONTRATO,  AVG(c.VALOR_MENSALIDADE) AS VALOR_MEDIO
FROM EMPRESA e JOIN CONTRATO c ON
e.ID_EMPRESA = c.ID_EMPRESA
WHERE (c.SITUACAO_FINANCEIRA LIKE "Inadimplente" OR c.STATUS_CONTRATO LIKE "Suspenso") AND c.VALOR_MENSALIDADE >=200.00
GROUP BY c.PLANO_CONTRATO;

SELECT MIN(c.VALOR_MENSALIDADE) AS VALOR_MINIMO , MAX(c.VALOR_MENSALIDADE)
FROM EMPRESA e JOIN CONTRATO c ON
e.ID_EMPRESA = c.ID_EMPRESA
WHERE c.SITUACAO_FINANCEIRA <> "Regular" AND c.PLANO_CONTRATO IN ("Premium", "Enterprise");

SELECT e.RAZAO_SOCIAL, COUNT(c.ID_CONTRATO) AS QTD_CONTRATOS
FROM EMPRESA e 
JOIN CONTRATO c ON e.ID_EMPRESA = c.ID_EMPRESA
WHERE c.STATUS_CONTRATO = "Ativo" 
GROUP BY e.RAZAO_SOCIAL           
HAVING COUNT(c.ID_CONTRATO) > 1; 

SELECT e.PLANO_CONTRATO