--============Pedidos Cliente============

CREATE DATABASE SISTEMA_VENDAS;
USE SISTEMA_VENDAS;
SHOW TABLES;
CREATE TABLE CLIENTE(
	ID_CLIENTE INT AUTO_INCREMENT,
	NOME VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(20) DEFAULT "Ponta Grossa",
	PRIMARY KEY (ID_CLIENTE)
);
CREATE TABLE PEDIDO(
	ID_PEDIDO INT AUTO_INCREMENT,
	VALOR_TOTAL DECIMAL(20,2) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	PRIMARY KEY(ID_PEDIDO),
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON UPDATE RESTRICT ON DELETE RESTRICT
);
DESC CLIENTE;
DESC PEDIDO;

ALTER TABLE CLIENTE ADD COLUMN EMAIL VARCHAR(150) NOT NULL AFTER NOME;
ALTER TABLE PEDIDO ADD COLUMN STATUS VARCHAR(30) DEFAULT "Processando";


INSERT INTO CLIENTE(NOME, EMAIL)
VALUES ("Tiago Malanczen","tiago@email.com");
INSERT INTO CLIENTE(NOME, EMAIL, CIDADE)
VALUES ("Marcos Santos", "marcos@email.com","Curitiba"),
       ("Aline Souza","aline@email.com","Londrina");

INSERT INTO PEDIDO(VALOR_TOTAL, ID_CLIENTE)
VALUES (250.0, 1),
       (1200, 1),
       (850, 2);

SELECT *FROM CLIENTE WHERE (CIDADE = "Curitiba" AND EMAIL LIKE "%email.com");
SELECT *FROM PEDIDO WHERE VALOR_TOTAL NOT BETWEEN 100 AND 500;
SELECT c.NOME, p.VALOR_TOTAL
FROM CLIENTE c JOIN PEDIDO p 
ON c.ID_CLIENTE = p.ID_CLIENTE;
SELECT c.NOME, p.VALOR_TOTAL as teste
FROM CLIENTE c LEFT JOIN PEDIDO p
ON c.ID_CLIENTE = p.ID_CLIENTE
group by C.nome;

SELECT c.NOME , SUM(p.VALOR_TOTAL) AS VALOR_TOTAL
FROM CLIENTE c JOIN PEDIDO p ON
c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY c.NOME;

SELECT c.CIDADE, COUNT(p.ID_PEDIDO)  AS QUANTIDADE_POR_CIDADE
FROM CLIENTE c JOIN PEDIDO p ON 
c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY c.CIDADE; 

SELECT c.NOME, MIN(p.VALOR_TOTAL) AS MINIMO, MAX (p.VALOR_TOTAL) AS MAXIMO
FROM CLIENTE c JOIN PEDIDO p ON 
c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY C.NOME;

    

SELECT ID_CLIENTE,
     COUNT(*) AS QUANTIDADE
FROM PEDIDO
GROUP BY ID_CLIENTE;

SELECT p.STATUS, SUM(p.VALOR_TOTAL) TOTAL_POR_PEDIDO
FROM CLIENTE c JOIN PEDIDO p ON
c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY p.STATUS;

SELECT c.NOME, AVG(VALOR_TOTAL) AS MEDIA_GASTO
FROM CLIENTE c JOIN PEDIDO p ON
c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY c.NOME;

SELECT c.CIDADE, MAX(p.VALOR_TOTAL) AS VALOR_MAXIMO
FROM CLIENTE c JOIN PEDIDO p ON
c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY c.CIDADE;

SELECT SUM(VALOR_TOTAL) AS TOTAL_GASTO
FROM PEDIDO;


