-- ==================SISTEMA_LOGISTICA================== 

CREATE DATABASE SISTEMA_LOGISTICA;
USE SISTEMA_LOGISTICA;

CREATE TABLE VEICULO(
    ID_VEICULO INT AUTO_INCREMENT ,
    MODELO VARCHAR(50) NOT NULL,
    PLACA VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID_VEICULO)
);
CREATE TABLE ENTREGA(
    ID_ENTREGA INT AUTO_INCREMENT,
    CIDADE_DESTINO VARCHAR(100) NOT NULL,
    STATUS_ENTREGA VARCHAR(30) DEFAULT "Pendente",
    VALOR_FRETE DECIMAL(10,2) NOT NULL, 
    DATA_ENVIO DATE,
    ID_VEICULO INT NOT NULL,
    PRIMARY KEY(ID_ENTREGA),
    FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO) ON DELETE RESTRICT ON UPDATE RESTRICT
);

SHOW TABLES;
DESC ENTREGA;
DESC VEICULO;

