-- ================SISTEMA ACADEMIA================

CREATE DATABASE SISTEMA_ACADEMIA;
USE SISTEMA_ACADEMIA;

CREATE TABLE PLANO (
    ID_PLANO INT AUTO_INCREMENT,
    NOME_PLANO VARCHAR(100),
    PRECO DECIMAL(10,2),
    PRIMARY KEY(ID_PLANO)
);
CREATE TABLE ALUNO(
    ID_ALUNO INT AUTO_INCREMENT,
    NOME_ALUNO VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT "Ativo",
    ID_PLANO INT NOT NULL,
    PRIMARY KEY(ID_ALUNO),
    FOREIGN KEY(ID_PLANO) REFERENCES PLANO(ID_PLANO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE PLANO  MODIFY COLUMN NOME_PLANO  VARCHAR(100) NOT NULL;
ALTER TABLE PLANO MODIFY COLUMN PRECO DECIMAL(10,2) NOT NULL;

INSERT INTO PLANO(NOME_PLANO, PRECO)
VALUES  ("Smart", 99.00),
        ("Black",  149.90),
        ("Platinum", 249.90);
INSERT INTO ALUNO(NOME_ALUNO, ID_PLANO)
VALUES  ("Tiago Silva", 1),
        ("Marcos Santos",2),
        ("Aline Souza",  1.);

SELECT *FROM ALUNO;
SELECT *FROM PLANO;

SELECT p.NOME_PLANO, SUM(p.PRECO) AS VALOR_TOTAL_PLANO
FROM PLANO p JOIN ALUNO a ON
p.ID_PLANO = a.ID_PLANO
GROUP BY p.NOME_PLANO;

SELECT p.NOME_PLANO, COUNT(a.ID_ALUNO) AS TOTAL_ALUNOS
FROM ALUNO a JOIN PLANO p ON
p.ID_PLANO = a.ID_PLANO
GROUP BY p.NOME_PLANO;

SELECT AVG(p.PRECO) AS VALOR_MEDIO
FROM ALUNO a JOIN PLANO p ON
p.ID_PLANO = a.ID_PLANO;