CREATE DATABASE IF NOT EXISTS SISTEMA_ESTACIONAMENTO;
USE SISTEMA_ESTACIONAMENTO;

CREATE TABLE CLIENTE(

    ID_CLIENTE INT AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR (15) NOT NULL,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE VEICULO(

    ID_VEICULO INT AUTO_INCREMENT,
    PLACA VARCHAR(8) NOT NULL,
    TIPO VARCHAR(200) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    PRIMARY KEY (ID_VEICULO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE TABLE CONTRATO(

    ID_CONTRATO INT AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DATA_INICIO DATE NOT NULL,
    VALOR_MENSAL DECIMAL(10, 2),
    PRIMARY KEY(ID_CONTRATO),
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON UPDATE RESTRICT ON DELETE RESTRICT
    
);

SHOW TABLES;

INSERT INTO CLIENTE(NOME, CPF) 
VALUES ('Tiago Malanczen', '111.111.111-11'),
       ('Lucas Alves', '222.222.222-22');
INSERT INTO VEICULO(PLACA, TIPO, ID_CLIENTE)
VALUES ('ABC-1234','Carro',1),
       ('XYZ-5678','Moto',1),
       ('KGB-9999','Carro',2);
    
INSERT INTO CONTRATO (id_cliente, data_inicio, valor_mensal) VALUES (1, '2021-04-15', 150.00), 
       (2, '2026-01-10', 200.00);

SELECT *FROM CLIENTE;
SELECT *FROM VEICULO;
SELECT *FROM CONTRATO;

SELECT c.NOME AS CLIENTE_COM_CARRO
FROM CLIENTE c JOIN VEICULO v ON 
c.ID_CLIENTE = v.ID_CLIENTE
WHERE v.TIPO LIKE "Carro"
ORDER BY c.NOME;

SELECT c.NOME, COUNT(v.ID_VEICULO) AS QUANTIDADE_VEICULOS
FROM CLIENTE c JOIN VEICULO v ON 
c.ID_CLIENTE = v.ID_CLIENTE
GROUP BY c.NOME;

