-- ==================SISTEMA_LOGISTICA================== 

CREATE DATABASE SISTEMA_LOGISTICA;
USE SISTEMA_LOGISTICA;

CREATE TABLE VEICULO(
    ID_VEICULO INT AUTO_INCREMENT ,
    MODELO VARCHAR(50) NOT NULL,
    PLACA VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID_VEICULO)
);
CREATE TABLE ENTREGA(
    ID_ENTREGA INT AUTO_INCREMENT,
    CIDADE_DESTINO VARCHAR(100) NOT NULL,
    STATUS_ENTREGA VARCHAR(30) DEFAULT "Pendente",
    VALOR_FRETE DECIMAL(10,2) NOT NULL, 
    DATA_ENVIO DATE,
    ID_VEICULO INT NOT NULL,
    PRIMARY KEY(ID_ENTREGA),
    FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO) ON DELETE RESTRICT ON UPDATE RESTRICT
);

SHOW TABLES;
DESC ENTREGA;
DESC VEICULO;

INSERT INTO VEICULO(MODELO, PLACA)
VALUES  ("Fiorino", "AAA-1111"),
        ("Caminhão Cargo", "BBB-2222");

INSERT INTO ENTREGA(CIDADE_DESTINO, STATUS_ENTREGA, VALOR_FRETE, DATA_ENVIO, ID_VEICULO)
VALUES  ("Ponta Grossa","Entregue", 150.00, '2026-05-10', 1),
        ("Curitiba", "Em Transito", 450.00, '2026-05-20', 2.),
        ("Ponta Grossa", "Pendente",120.00, NULL, 1),
        ("Londrina", "Entregue", 600.00,'2026-05-25', 2);

SELECT *FROM VEICULO;
SELECT *FROM ENTREGA;