-- ==================SISTEMA_LOGISTICA================== 

CREATE DATABASE SISTEMA_LOGISTICA;
USE SISTEMA_LOGISTICA;

CREATE TABLE VEICULO(
    ID_VEICULO INT AUTO_INCREMENT ,
    MODELO VARCHAR(50) NOT NULL,
    PLACA VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID_VEICULO)
);
CREATE TABLE ENTREGA(
    ID_ENTREGA INT AUTO_INCREMENT,
    CIDADE_DESTINO VARCHAR(100) NOT NULL,
    STATUS_ENTREGA VARCHAR(30) DEFAULT "Pendente",
    VALOR_FRETE DECIMAL(10,2) NOT NULL, 
    DATA_ENVIO DATE,
    ID_VEICULO INT NOT NULL,
    PRIMARY KEY(ID_ENTREGA),
    FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO) ON DELETE RESTRICT ON UPDATE RESTRICT
);

SHOW TABLES;
DESC ENTREGA;
DESC VEICULO;

INSERT INTO VEICULO(MODELO, PLACA)
VALUES  ("Fiorino", "AAA-1111"),
        ("Caminhão Cargo", "BBB-2222");

INSERT INTO ENTREGA(CIDADE_DESTINO, STATUS_ENTREGA, VALOR_FRETE, DATA_ENVIO, ID_VEICULO)
VALUES  ("Ponta Grossa","Entregue", 150.00, '2026-05-10', 1),
        ("Curitiba", "Em Transito", 450.00, '2026-05-20', 2.),
        ("Ponta Grossa", "Pendente",120.00, NULL, 1),
        ("Londrina", "Entregue", 600.00,'2026-05-25', 2);

SELECT *FROM VEICULO;
SELECT *FROM ENTREGA;

SELECT *FROM ENTREGA WHERE VALOR_FRETE BETWEEN 100.0 AND 500.0 
AND DATA_ENVIO IS NOT NULL AND CIDADE_DESTINO LIKE "%a";

SELECT v.MODELO, SUM(e.VALOR_FRETE) AS VALOR_MODULO
FROM VEICULO v JOIN ENTREGA e ON
v.ID_VEICULO = e.ID_VEICULO 
WHERE (e.STATUS_ENTREGA = "Entregue" OR e.STATUS_ENTREGA = "Em Transito") AND v.MODELO LIKE "C%"
GROUP BY v.MODELO;

SELECT e.CIDADE_DESTINO, AVG(e.VALOR_FRETE) AS VALOR_MEDIO
FROM VEICULO v JOIN ENTREGA e ON
v.ID_VEICULO = e.ID_VEICULO
WHERE v.PLACA <> "BBB-222"
-- ==================SISTEMA_LOGISTICA================== 

CREATE DATABASE SISTEMA_LOGISTICA;
USE SISTEMA_LOGISTICA;

CREATE TABLE VEICULO(
    ID_VEICULO INT AUTO_INCREMENT ,
    MODELO VARCHAR(50) NOT NULL,
    PLACA VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID_VEICULO)
);
CREATE TABLE ENTREGA(
    ID_ENTREGA INT AUTO_INCREMENT,
    CIDADE_DESTINO VARCHAR(100) NOT NULL,
    STATUS_ENTREGA VARCHAR(30) DEFAULT "Pendente",
    VALOR_FRETE DECIMAL(10,2) NOT NULL, 
    DATA_ENVIO DATE,
    ID_VEICULO INT NOT NULL,
    PRIMARY KEY(ID_ENTREGA),
    FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO) ON DELETE RESTRICT ON UPDATE RESTRICT
);

SHOW TABLES;
DESC ENTREGA;
DESC VEICULO;

INSERT INTO VEICULO(MODELO, PLACA)
VALUES  ("Fiorino", "AAA-1111"),
        ("Caminhão Cargo", "BBB-2222");

INSERT INTO ENTREGA(CIDADE_DESTINO, STATUS_ENTREGA, VALOR_FRETE, DATA_ENVIO, ID_VEICULO)
VALUES  ("Ponta Grossa","Entregue", 150.00, '2026-05-10', 1),
        ("Curitiba", "Em Transito", 450.00, '2026-05-20', 2.),
        ("Ponta Grossa", "Pendente",120.00, NULL, 1),
        ("Londrina", "Entregue", 600.00,'2026-05-25', 2);

SELECT *FROM VEICULO;
SELECT *FROM ENTREGA;

SELECT *FROM ENTREGA WHERE VALOR_FRETE BETWEEN 100.0 AND 500.0 
AND DATA_ENVIO IS NOT NULL AND CIDADE_DESTINO LIKE "%a";

SELECT v.MODELO, SUM(e.VALOR_FRETE) AS VALOR_MODULO
FROM VEICULO v JOIN ENTREGA e ON
v.ID_VEICULO = e.ID_VEICULO 
WHERE (e.STATUS_ENTREGA = "Entregue" OR e.STATUS_ENTREGA = "Em Transito") AND v.MODELO LIKE "C%"
GROUP BY v.MODELO;

SELECT e.CIDADE_DESTINO, AVG(e.VALOR_FRETE) AS VALOR_MEDIO
FROM VEICULO v JOIN ENTREGA e ON
v.ID_VEICULO = e.ID_VEICULO
WHERE v.PLACA <> "BBB-2222"
GROUP BY e.CIDADE_DESTINO;