CREATE DATABASE IF NOT EXISTS UNIVERSIDADE_UTFPR;
USE UNIVERSIDADE_UTFPR;

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    SIGLA VARCHAR(10) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO)
);

CREATE TABLE CURSO (
    ID_CURSO INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    SIGLA VARCHAR(10) NOT NULL,
    CARGA_HORARIA INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (ID_CURSO),
    CONSTRAINT FK_CURSO_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) 
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE EQUIPAMENTO (
    ID_EQUIPAMENTO INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    QUANT_EXISTENTE INT NOT NULL,
    CONSTRAINT PK_EQUIPAMENTO PRIMARY KEY (ID_EQUIPAMENTO)
);

CREATE TABLE SALA (
    ID_SALA INT AUTO_INCREMENT,
    SIGLA VARCHAR(10) NOT NULL,
    TIPO_SALA ENUM('Teórica', 'Laboratório', 'Auditório', 'Gabinete Professor') NOT NULL,
    CAPACIDADE INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    CONSTRAINT PK_SALA PRIMARY KEY (ID_SALA),
    CONSTRAINT FK_SALA_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) 
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE SALAEQUIPAMENTO (
    ID_SALA INT NOT NULL,
    ID_EQUIPAMENTO INT NOT NULL,
    QUANT_ALOCADA INT NOT NULL,
    CONSTRAINT PK_SALAEQUIPAMENTO PRIMARY KEY (ID_SALA, ID_EQUIPAMENTO),
    CONSTRAINT FK_SE_SALA FOREIGN KEY (ID_SALA) 
        REFERENCES SALA(ID_SALA) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT FK_SE_EQUIPAMENTO FOREIGN KEY (ID_EQUIPAMENTO) 
        REFERENCES EQUIPAMENTO(ID_EQUIPAMENTO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE ENDERECO (
    ID_ENDERECO INT AUTO_INCREMENT,
    UF CHAR(2) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    RUA VARCHAR(150) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    DATA_DEMISSAO DATE NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    ID_ENDERECO INT NOT NULL,
    ID_DEPARTAMENTO INT NOT NULL,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO),
    CONSTRAINT FK_FUNC_ENDERECO FOREIGN KEY (ID_ENDERECO) 
        REFERENCES ENDERECO(ID_ENDERECO) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT FK_FUNC_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) 
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO) ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- 8. Tabela EVENTO
CREATE TABLE EVENTO (
    ID_EVENTO INT AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO TEXT NULL,
    SIGLA VARCHAR(10) NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO)
);

CREATE TABLE ALOCACAO (
    ID_ALOCACAO INT AUTO_INCREMENT,
    ID_EVENTO INT NOT NULL,
    ID_SALA INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    DATA_ALOCACAO DATE NOT NULL,
    DATA_INICIO_RESERVA DATE NOT NULL,
    DATA_TERMINO_RESERVA DATE NOT NULL,
    HORA_INICIO_RESERVA TIME NOT NULL,
    HORA_TERMINO_RESERVA TIME NOT NULL,
    DIA_SEMANA ENUM('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado') NOT NULL,
    CONSTRAINT PK_ALOCACAO PRIMARY KEY (ID_ALOCACAO),
    CONSTRAINT FK_ALOC_EVENTO FOREIGN KEY (ID_EVENTO) 
        REFERENCES EVENTO(ID_EVENTO) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT FK_ALOC_SALA FOREIGN KEY (ID_SALA) 
        REFERENCES SALA(ID_SALA) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT FK_ALOC_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) 
        REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON UPDATE RESTRICT ON DELETE RESTRICT
);


SHOW TABLES;

